---
- hosts: localhost
  gather_facts: no

  vars:
    target: "10.119.99.123"
    username: 'admin'
    password: 'Password123!'
    asset_name: 'MySQL'
    #Following vars different from VC GUI names. Require to find manul restore from PPDM GUI and check values.
    datacenter_id: 'datacenter-3'
    host_id: 'host-10'
    #cluster_id: 'domain-c6'
    datastore_id: 'datastore-12'
    filter: 'filter=name%20eq%20%22{{ asset_name }}%22'
    filter2: 'filter=type%20eq%20%22VCENTER%22'

  tasks:

    - name: Authenticate with PPDM
      uri:
        url: "https://{{ target }}:8443/api/v2/login"
        method: POST
        body:
          username: '{{ username }}'
          password: '{{ password }}'
        body_format: json
        headers:
          Content-Type: 'application/json'
        validate_certs: no
      register: response

    - debug:
        msg: "Bearer {{ response.json.access_token }}"

# Restore API call requires passing asset ID
    - name: Getting asset ID
      uri:
        url: "https://{{ target }}:8443/api/v2/assets?{{ filter }}"
        method: GET
        headers:
          Content-Type: 'application/json'
          Authorization: 'Bearer {{ response.json.access_token }}'
        validate_certs: no
      register: assets

    - debug:
        var: assets

# Restore API call requires passing backup ID
    - name: Get latest backup ID
      uri:
        url: "https://{{ target }}:8443/api/v2/assets/{{ assets.json.content.0.id }}/copies"
        method: GET
        headers:
          Content-Type: 'application/json'
          Authorization: 'Bearer {{ response.json.access_token }}'
        validate_certs: no
      register: backupcopies

    - debug:
            msg: "Backup ID {{ backupcopies.json.content.0.id }} ended at {{ backupcopies.json.content.0.endTime }}"

# Restore API call get vcenter ID
    - name: Get vcenter ID
      uri:
        url: "https://{{ target }}:8443/api/v2/inventory-sources?{{ filter2 }}"
        method: GET
        headers:
          Content-Type: 'application/json'
          Authorization: 'Bearer {{ response.json.access_token }}'
        validate_certs: no
      register: vcenters

    - debug:
       var: vcenters

    - name: Perform the restore
      uri:
        url: "https://{{ target }}:8443/api/v2/restored-copies"
        method: POST
        body:
          description: "Restore VM to New"
          copyId: "{{ backupcopies.json.content.0.id }}"
          restoreType: "TO_ALTERNATE"
          restoredCopiesDetails:
            targetVmInfo:
              inventorySourceId: "{{ vcenters.json.content.0.id }}"
              vmName: "Restored_{{ asset_name }}"
              dataCenterMoref: "{{ datacenter_id }}"
              hostMoref: "{{ host_id }}"
              dataStoreMoref: "{{ datastore_id }}"
              vmPowerOn: false
              vmReconnectNic: false
        body_format: json
        headers:
          Content-Type: 'application/json'
          Authorization: 'Bearer {{ response.json.access_token }}'
        validate_certs: no
        status_code: 201
      register: restore_job

    - debug:
            msg: "{{ restore_job }}"


